"""
Django settings for B2B project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv
import dj_database_url
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--ix!$=7edqo+o(gq*4ig1*ef=*h^d1ptko5pt*1yhzcxkb+7z!')

# CONFIGURACIÓN LOCAL: En desarrollo esto debe ser True para ver los errores.
# CONFIGURACIÓN PRODUCCIÓN: Cambiar a False (o usar os.getenv('DEBUG', 'False') == 'True')
DEBUG = True

# CONFIGURACIÓN LOCAL: Permite cualquier host ('*') en desarrollo.
# CONFIGURACIÓN PRODUCCIÓN: Añade el dominio real que te dé la plataforma (ej. ['tu-app.onrender.com'])
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- Librerías de Terceros (se mantienen para la API REST si se necesita) ---
    'rest_framework',
    'corsheaders',
    # --- Aplicaciones MVT B2B ---
    'core',          # App principal: vistas, templates, carrito, forms
    'catalog',
    'users',
    'orders',
    'subscriptions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'B2B.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Apunta a la carpeta global de templates en la raíz del proyecto
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context processor para el badge del carrito en el navbar
                'core.context_processors.carrito_global',
            ],
        },
    },
]

WSGI_APPLICATION = 'B2B.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {
    'default': dj_database_url.config(
        # CONFIGURACIÓN LOCAL (Docker Compose): 
        # Apunta a la instancia de PostgreSQL levantada mediante tu archivo docker-compose.yml, usando localhost y el puerto expuesto
        default=os.getenv('DATABASE_URL', 'postgres://bazar_admin:bazar_password@localhost:5434/bazar_db'),
        
        # CONFIGURACIÓN PRODUCCIÓN (Ej. Render, AWS):
        # Al subir a producción, la plataforma inyectará la variable de entorno 'DATABASE_URL'.
        # dj_database_url leerá esa variable y reemplazará automáticamente esta conexión local
        # por la de producción, sin que tengas que tocar este código.
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'   # Español Ecuador

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Habilita la compresión y el almacenamiento en caché a largo plazo
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Imágenes de productos, documentos de verificación)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'users.CustomUser'

# -----------------------------------------------------------------------
# AUTENTICACIÓN MVT — Sesiones nativas de Django
# -----------------------------------------------------------------------
LOGIN_URL = 'login'           # URL a la que redirige @login_required
LOGIN_REDIRECT_URL = 'catalogo'  # Tras login exitoso
LOGOUT_REDIRECT_URL = 'login'   # Tras logout

# Configuración de sesiones (cookie-based, almacenadas en DB)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 días
SESSION_SAVE_EVERY_REQUEST = False

# -----------------------------------------------------------------------
# API REST (se mantiene para endpoints de integración futura)
# -----------------------------------------------------------------------
# Permite peticiones desde herramientas de testing o apps móviles
# CONFIGURACIÓN LOCAL: True permite que cualquier origen consuma la API (ideal en local).
# CONFIGURACIÓN PRODUCCIÓN: Cambiar a False y configurar CORS_ALLOWED_ORIGINS con los dominios permitidos.
CORS_ALLOW_ALL_ORIGINS = True

# Se ha eliminado cualquier bloque relacionado a REST_FRAMEWORK para evitar confusiones con JWT.
# Django REST Framework utilizará sus valores por defecto (como SessionAuthentication).
