# Generated by Django 5.2.15 on 2026-06-30 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Electrónica, Hogar, Ropa', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(help_text='URL amigable para SEO', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(help_text='Código único de inventario', max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_publico', models.DecimalField(decimal_places=2, help_text='Precio para visitantes o consumidores finales', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio_minorista', models.DecimalField(decimal_places=2, help_text='Precio con descuento exclusivo para tiendas (B2B)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('moq', models.PositiveIntegerField(default=1, help_text='Cantidad Mínima de Pedido (Minimum Order Quantity)')),
                ('multiplo_lote', models.PositiveIntegerField(default=1, help_text='Unidades por lote (Ej: Si es 6, solo se vende de 6 en 6)')),
                ('activo', models.BooleanField(default=True, help_text='Si es False, se oculta del catálogo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalog.categoria')),
                ('proveedor', models.ForeignKey(limit_choices_to={'rol': 'MAYORISTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='productos_ofrecidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
