# Generated by Django 5.2.15 on 2026-06-30 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(help_text='Ej: Básico, Premium, VIP', max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_productos', models.PositiveIntegerField(help_text='Cantidad máxima de productos que puede publicar')),
                ('destacado', models.BooleanField(default=False, help_text='Si es True, se resalta en el frontend')),
            ],
            options={
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(help_text='Fecha en la que expira el plan')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=20)),
                ('transaccion_pasarela_id', models.CharField(blank=True, help_text='ID del pago en Stripe/PayPal', max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plansuscripcion')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'MAYORISTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_activa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
