# Generated by Django 5.2.15 on 2026-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documento_verificacion',
            field=models.FileField(blank=True, help_text='Sube RUC o Patente Comercial', null=True, upload_to='documentos_fiscales/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_fin_suscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_actual',
            field=models.CharField(default='PRUEBA_GRATUITA', help_text='Plan activo del usuario', max_length=50),
        ),
    ]
